In [1]:
import numpy as np
import pandas as pd
from time import time
from IPython.display import display

# Load the sessions dataset
data = pd.read_csv("Example test.csv")

# Display the first record
display(data.head())

Language Search Engine Destination Searched   Label
0  English        Google              Florida      US
1  English         Baidu                 Xian   China
2   French        Google                Paris  France
3   French        Google             Montreal  Canada
4  English        Google              Florida      US

In [2]:
# Split the data into features and target label
label_raw = data['Label']
features_raw = data.drop('Label', axis = 1)

In [4]:
# TODO: One-hot encode the 'features_log_minmax_transform' data using pandas.get_dummies()
features_final = pd.get_dummies(features_raw)

# TODO: Encode the 'income_raw' data to numerical values
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
le.fit(label_raw)
label = le.transform(label_raw)

# Print the number of features after one-hot encoding
encoded = list(features_final.columns)
print ("{} total features after one-hot encoding.".format(len(encoded)))
print(encoded)

8 total features after one-hot encoding.
['Language_English', 'Language_French', 'Search Engine_Baidu', 'Search Engine_Google', 'Destination Searched_Florida', 'Destination Searched_Montreal', 'Destination Searched_Paris', 'Destination Searched_Xian']


In [5]:
# Import train_test_split
from sklearn.cross_validation import train_test_split

# Split the 'features' and 'income' data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features_final, 
                                                    label, 
                                                    test_size = 0.2, 
                                                    random_state = 0)

# Show the results of the split
print ("Training set has {} samples.".format(X_train.shape[0]))
print ("Testing set has {} samples.".format(X_test.shape[0]))
print(X_train.head())
print(y_train)

Training set has 79 samples.
Testing set has 20 samples.
    Language_English  Language_French  Search Engine_Baidu  \
43                 0                1                    0   
62                 1                0                    0   
3                  0                1                    0   
71                 1                0                    1   
45                 1                0                    1   

    Search Engine_Google  Destination Searched_Florida  \
43                     1                             0   
62                     1                             1   
3                      1                             0   
71                     0                             0   
45                     0                             0   

    Destination Searched_Montreal  Destination Searched_Paris  \
43                              1                           0   
62                              0                           0   
3                         

C:\Users\Owner\Anaconda2\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import numpy as np

#X_train, y_train = make_classification(n_samples=79, n_features=8, n_informative=5, n_classes=4, random_state=1)
y2 = y_train
Y = np.vstack((y_train, y2)).T

forest = RandomForestClassifier(n_estimators=10, random_state=1)
multi_target_forest = MultiOutputClassifier(forest, n_jobs=-1)
multi_target_forest.fit(X_train, Y).predict(X_train)

print(X_test.head())
print(multi_target_forest.predict_proba(X_test))
#print(Y)
#for first_array in multi_target_forest.predict_proba(X_train):
#    for second_array in first_array:
#        sorted_array = sorted(second_array, reverse=True)
#        print(sorted_array)

    Language_English  Language_French  Search Engine_Baidu  \
26                 0                1                    0   
86                 0                1                    0   
2                  0                1                    0   
55                 1                0                    1   
75                 0                1                    0   

    Search Engine_Google  Destination Searched_Florida  \
26                     1                             0   
86                     1                             0   
2                      1                             0   
55                     0                             0   
75                     1                             0   

    Destination Searched_Montreal  Destination Searched_Paris  \
26                              0                           1   
86                              0                           1   
2                               0                           1   
55                

In [7]:
print(y_test)

[2 2 2 1 2 3 3 3 3 0 2 0 2 1 0 2 2 3 1 3]


In [8]:
y_array =np.asarray(y_test)

print(y_array)

[2 2 2 1 2 3 3 3 3 0 2 0 2 1 0 2 2 3 1 3]


In [9]:
array_to_compare_predictions=[]
nested_array=[]
for element in y_array:
    i=0
    nested_array=[]
    while i < 4:
        if i == element:
            nested_array.append(1)
            i=i+1
        else:
            nested_array.append(0)
            i=i+1
    array_to_compare_predictions.append(nested_array)
        
print(array_to_compare_predictions)

[[0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 1], [0, 1, 0, 0], [0, 0, 0, 1]]


In [10]:
Array_to_compare_predictions =np.asarray(array_to_compare_predictions)

In [10]:
#print(array_to_compare_predictions.shape)

In [11]:
print(Array_to_compare_predictions.shape)

(20L, 4L)


In [12]:
print(Array_to_compare_predictions)

[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 0 1]]


In [13]:
multi_target_forest.predict_proba(X_test)[0].shape

(20L, 4L)

In [14]:
print(multi_target_forest.predict_proba(X_test)[0][19])

[ 0.  0.  0.  1.]


In [15]:
print(multi_target_forest.predict_proba(X_test)[0])

[[ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]]


In [16]:
true_values = Array_to_compare_predictions

In [17]:
predictions = multi_target_forest.predict_proba(X_test)[0]

In [18]:
#https://stackoverflow.com/questions/6422700/how-to-get-indices-of-a-sorted-array-in-python
#https://stackoverflow.com/questions/6193498/pythonic-way-to-find-maximum-value-and-its-index-in-a-list
#https://stackoverflow.com/questions/5284646/rank-items-in-an-array-using-python-numpy

import operator

maximal_value_tracking_index =[]

for element in predictions:
    order = element.argsort()
    rank = order.argsort()
 #   rank = rank +1
 #   sorted_rank=sorted(rank, reverse=True)
    maximal_value_tracking_index.append(rank+1)

print(maximal_value_tracking_index)
print(order)
print(rank)

[array([1, 2, 4, 3], dtype=int64), array([1, 2, 4, 3], dtype=int64), array([1, 2, 4, 3], dtype=int64), array([1, 4, 2, 3], dtype=int64), array([1, 2, 4, 3], dtype=int64), array([1, 2, 3, 4], dtype=int64), array([1, 2, 3, 4], dtype=int64), array([1, 2, 3, 4], dtype=int64), array([1, 2, 3, 4], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([1, 2, 4, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([1, 2, 4, 3], dtype=int64), array([1, 4, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([1, 2, 4, 3], dtype=int64), array([1, 2, 4, 3], dtype=int64), array([1, 2, 3, 4], dtype=int64), array([1, 4, 2, 3], dtype=int64), array([1, 2, 3, 4], dtype=int64)]
[0 1 2 3]
[0 1 2 3]


In [34]:
maximal_value_tracking_index = np.asarray(maximal_value_tracking_index)

In [36]:
label_spelled_out = ['CA', 'CN', 'FR', 'US'] #these labels are consistent with the predictions and true. one hot encoding puts the countries in descending order. Apply sort, in case any countries out of order

In [37]:
sort_label_spelled_out = sorted(label_spelled_out)

In [66]:
country_labels = np.tile(np.asarray(sort_label_spelled_out), (20,1)) #create an array with the same shape as the training set, #https://stackoverflow.com/questions/1550130/cloning-row-or-column-vectors

In [67]:
country_labels

array([['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US'],
       ['CA', 'CN', 'FR', 'US']],
      dtype='|S2')

In [108]:
#for each element, in each array, assign country_labels with the value in maximal value tracking. Remember, 4 is the largest and considerd the country most likely to vist
# https://stackoverflow.com/questions/6618515/sorting-list-based-on-values-from-another-list

i=0
country_labels_maximal_tracking = []
for element in country_labels:
    country_labels_maximal_tracking.append(zip(maximal_value_tracking_index[i],country_labels[i]))
    i=i+1
    

In [109]:
country_labels_maximal_tracking

[[(1, 'CA'), (2, 'CN'), (4, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (4, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (4, 'FR'), (3, 'US')],
 [(1, 'CA'), (4, 'CN'), (2, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (4, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (3, 'FR'), (4, 'US')],
 [(1, 'CA'), (2, 'CN'), (3, 'FR'), (4, 'US')],
 [(1, 'CA'), (2, 'CN'), (3, 'FR'), (4, 'US')],
 [(1, 'CA'), (2, 'CN'), (3, 'FR'), (4, 'US')],
 [(4, 'CA'), (1, 'CN'), (2, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (4, 'FR'), (3, 'US')],
 [(4, 'CA'), (1, 'CN'), (2, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (4, 'FR'), (3, 'US')],
 [(1, 'CA'), (4, 'CN'), (2, 'FR'), (3, 'US')],
 [(4, 'CA'), (1, 'CN'), (2, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (4, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (4, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (3, 'FR'), (4, 'US')],
 [(1, 'CA'), (4, 'CN'), (2, 'FR'), (3, 'US')],
 [(1, 'CA'), (2, 'CN'), (3, 'FR'), (4, 'US')]]

In [110]:
#sort the labels in reverse order
for element in country_labels_maximal_tracking:
    element.sort(reverse=True)

In [111]:
country_labels_maximal_tracking

[[(4, 'FR'), (3, 'US'), (2, 'CN'), (1, 'CA')],
 [(4, 'FR'), (3, 'US'), (2, 'CN'), (1, 'CA')],
 [(4, 'FR'), (3, 'US'), (2, 'CN'), (1, 'CA')],
 [(4, 'CN'), (3, 'US'), (2, 'FR'), (1, 'CA')],
 [(4, 'FR'), (3, 'US'), (2, 'CN'), (1, 'CA')],
 [(4, 'US'), (3, 'FR'), (2, 'CN'), (1, 'CA')],
 [(4, 'US'), (3, 'FR'), (2, 'CN'), (1, 'CA')],
 [(4, 'US'), (3, 'FR'), (2, 'CN'), (1, 'CA')],
 [(4, 'US'), (3, 'FR'), (2, 'CN'), (1, 'CA')],
 [(4, 'CA'), (3, 'US'), (2, 'FR'), (1, 'CN')],
 [(4, 'FR'), (3, 'US'), (2, 'CN'), (1, 'CA')],
 [(4, 'CA'), (3, 'US'), (2, 'FR'), (1, 'CN')],
 [(4, 'FR'), (3, 'US'), (2, 'CN'), (1, 'CA')],
 [(4, 'CN'), (3, 'US'), (2, 'FR'), (1, 'CA')],
 [(4, 'CA'), (3, 'US'), (2, 'FR'), (1, 'CN')],
 [(4, 'FR'), (3, 'US'), (2, 'CN'), (1, 'CA')],
 [(4, 'FR'), (3, 'US'), (2, 'CN'), (1, 'CA')],
 [(4, 'US'), (3, 'FR'), (2, 'CN'), (1, 'CA')],
 [(4, 'CN'), (3, 'US'), (2, 'FR'), (1, 'CA')],
 [(4, 'US'), (3, 'FR'), (2, 'CN'), (1, 'CA')]]

In [155]:
#extract the country from each subarray in country_labels_maximal_tracking
country_labels_sorted =[]
for element in country_labels_maximal_tracking:
    tracking_array = []
    i=0
    for sub_element in element:  
        if i<2:                                     #keep the first 5 elements in each subarray   
            tracking_array.append(sub_element[1])
            i=i+1
        else:
            None
    country_labels_sorted.append(tracking_array)

In [156]:
country_labels_sorted

[['FR', 'US'],
 ['FR', 'US'],
 ['FR', 'US'],
 ['CN', 'US'],
 ['FR', 'US'],
 ['US', 'FR'],
 ['US', 'FR'],
 ['US', 'FR'],
 ['US', 'FR'],
 ['CA', 'US'],
 ['FR', 'US'],
 ['CA', 'US'],
 ['FR', 'US'],
 ['CN', 'US'],
 ['CA', 'US'],
 ['FR', 'US'],
 ['FR', 'US'],
 ['US', 'FR'],
 ['CN', 'US'],
 ['US', 'FR']]

In [19]:
#https://stackoverflow.com/questions/6422700/how-to-get-indices-of-a-sorted-array-in-python
#https://stackoverflow.com/questions/6193498/pythonic-way-to-find-maximum-value-and-its-index-in-a-list

#index_of_reranking_predictions =[]
#for element in predictions:
#    index_of_reranking_predictions.append([i[0] for i in sorted(enumerate(element), key=lambda x:x[1])])

#print(index_of_reranking_predictions)

In [19]:
index_for_DCG =[]

i=0
for rank_element in maximal_value_tracking_index:
    if rank_element[y_test[i]] == 4: #maximal probability
        index_for_DCG.append(1)
    else:
        if rank_element[y_test[i]] == 1:  #1 is a special number to mean that both the prediction and true value matches at the last position.
            index_for_DCG.append(4)
        else:
            index_for_DCG.append(rank_element[y_test[i]])        
    i=i+1

print(index_for_DCG)    

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [20]:
import math

def calculate_nDCG(x):
    nDCG = [] 
    for element in x:
        nDCG.append((2 - 1)/math.log(element+1, 2))
    return nDCG

In [21]:
a_list = [1,0,0,0]
another_list = []

for i in range(20):
    another_list.append(a_list)
    a_list[0] = i + 0

print(another_list)

[[19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0], [19, 0, 0, 0]]


In [22]:
maximal_value_tracking_index_dummy =[]
another_list_to_array = np.array(another_list)

for element in another_list_to_array:
    order = element.argsort()
    rank = order.argsort()
    maximal_value_tracking_index_dummy.append(rank+1)

print(maximal_value_tracking_index_dummy)

[array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64), array([4, 1, 2, 3], dtype=int64)]


In [23]:
index_for_DCG_dummy =[]

i=0
for rank_element in maximal_value_tracking_index_dummy:
    if rank_element[y_test[i]] == 4:
        index_for_DCG_dummy.append(1)
    else:
        if rank_element[y_test[i]] == 1:
            index_for_DCG_dummy.append(4)
        else:
            index_for_DCG_dummy.append(rank_element[y_test[i]])
    i=i+1
  
print(index_for_DCG_dummy)    

[2, 2, 2, 4, 2, 3, 3, 3, 3, 1, 2, 1, 2, 4, 1, 2, 2, 3, 4, 3]


In [24]:
print(np.asarray((y_test)).tolist())

[2L, 2L, 2L, 1L, 2L, 3L, 3L, 3L, 3L, 0L, 2L, 0L, 2L, 1L, 0L, 2L, 2L, 3L, 1L, 3L]


In [25]:
calculate_nDCG(index_for_DCG_dummy)

[0.6309297535714574,
 0.6309297535714574,
 0.6309297535714574,
 0.43067655807339306,
 0.6309297535714574,
 0.5,
 0.5,
 0.5,
 0.5,
 1.0,
 0.6309297535714574,
 1.0,
 0.6309297535714574,
 0.43067655807339306,
 1.0,
 0.6309297535714574,
 0.6309297535714574,
 0.5,
 0.43067655807339306,
 0.5]

In [27]:
# Load the sessions dataset
sessions_data = pd.read_csv("sessions.csv")

In [28]:
# Display the first record
display(sessions_data.head())

user_id          action action_type        action_detail  \
0  d1mm9tcy42          lookup         NaN                  NaN   
1  d1mm9tcy42  search_results       click  view_search_results   
2  d1mm9tcy42          lookup         NaN                  NaN   
3  d1mm9tcy42  search_results       click  view_search_results   
4  d1mm9tcy42          lookup         NaN                  NaN   

       device_type  secs_elapsed  
0  Windows Desktop         319.0  
1  Windows Desktop       67753.0  
2  Windows Desktop         301.0  
3  Windows Desktop       22141.0  
4  Windows Desktop         435.0

In [29]:
sessions_data['action_type'] = sessions_data['action_type'].fillna('action_type_missing')

In [30]:
display(sessions_data.head())

user_id          action          action_type        action_detail  \
0  d1mm9tcy42          lookup  action_type_missing                  NaN   
1  d1mm9tcy42  search_results                click  view_search_results   
2  d1mm9tcy42          lookup  action_type_missing                  NaN   
3  d1mm9tcy42  search_results                click  view_search_results   
4  d1mm9tcy42          lookup  action_type_missing                  NaN   

       device_type  secs_elapsed  
0  Windows Desktop         319.0  
1  Windows Desktop       67753.0  
2  Windows Desktop         301.0  
3  Windows Desktop       22141.0  
4  Windows Desktop         435.0

In [31]:
sessions_data['action'] = sessions_data['action'].fillna('action_missing')

sessions_data['action_detail'] = sessions_data['action_detail'].fillna('action_detail_missing')

sessions_data['device_type'] = sessions_data['device_type'].fillna('device_type_missing')

sessions_data['secs_elapsed'] = sessions_data['secs_elapsed'].fillna(1)



In [32]:
sessions_data['user_id'].isnull().sum()

3563

In [33]:
print(sessions_data.shape)

(1048575, 6)


In [34]:
sessions_data_removed_blank_id = sessions_data[pd.notnull(sessions_data['user_id'])]

In [35]:
display(sessions_data_removed_blank_id.head())

user_id          action          action_type          action_detail  \
0  d1mm9tcy42          lookup  action_type_missing  action_detail_missing   
1  d1mm9tcy42  search_results                click    view_search_results   
2  d1mm9tcy42          lookup  action_type_missing  action_detail_missing   
3  d1mm9tcy42  search_results                click    view_search_results   
4  d1mm9tcy42          lookup  action_type_missing  action_detail_missing   

       device_type  secs_elapsed  
0  Windows Desktop         319.0  
1  Windows Desktop       67753.0  
2  Windows Desktop         301.0  
3  Windows Desktop       22141.0  
4  Windows Desktop         435.0

In [36]:
print(sessions_data_removed_blank_id.shape)

(1045012, 6)


In [37]:
userid_unique_values= sessions_data_removed_blank_id.user_id.unique() 

action_unique_values_bf = (sessions_data_removed_blank_id.action.unique()).reshape(244,1) #before flattened

action_type_unique_values_bf = (sessions_data_removed_blank_id.action_type.unique()).reshape(10,1) #before flattened

action_detail_unique_values_bf = sessions_data_removed_blank_id.action_detail.unique().reshape(105,1) #before flattened

device_type_bf = sessions_data_removed_blank_id.device_type.unique().reshape(14,1) #before flattened


#https://stackoverflow.com/questions/11264684/flatten-list-of-lists

action_unique_values = [val for sublist in action_unique_values_bf for val in sublist]

action_type_unique_values = [val for sublist in action_type_unique_values_bf for val in sublist]

action_detail_unique_values = [val for sublist in action_detail_unique_values_bf for val in sublist]

device_type = [val for sublist in device_type_bf for val in sublist]


In [38]:
#print(device_type.shape)

In [39]:
#http://pbpython.com/pandas-pivot-table-explained.html

sessions_data_pivoted = pd.pivot_table(sessions_data_removed_blank_id, index=["user_id"]).reset_index()

In [40]:
userid_unique_values = sessions_data_removed_blank_id.user_id.unique()

#action_unique_values = sessions_data_removed_blank_id.action.unique().reshape(1,244)

#action_type_unique_values = sessions_data_removed_blank_id.action_type.unique().reshape(1,10)

#action_detail_unique_values = sessions_data_removed_blank_id.action_detail.unique().reshape(1,105)

#device_type = sessions_data_removed_blank_id.device_type.unique().reshape(1,14)

In [41]:
#convert array to DataFrame

action_unique_values_df = pd.DataFrame(columns=sessions_data_removed_blank_id.action.unique().reshape(1,244)[0])

action_type_unique_values_df = pd.DataFrame(columns=sessions_data_removed_blank_id.action_type.unique().reshape(1,10)[0])

action_detail_unique_values_df = pd.DataFrame(columns=sessions_data_removed_blank_id.action_detail.unique().reshape(1,105)[0])

device_type_df = pd.DataFrame(columns=sessions_data_removed_blank_id.device_type.unique().reshape(1,14)[0])

In [ ]:

# #https://stackoverflow.com/questions/20995196/python-pandas-counting-and-summing-specific-conditions
# #https://stackoverflow.com/questions/10715965/add-one-row-in-a-pandas-dataframe

# i=0 #key to action_unique_values
# j=1 #key to the ith row in new action_unique_values dataframe


# for element in sessions_data_pivoted['user_id']:
#     current_user = sessions_data[sessions_data.user_id == element] #filter dataframe for that user_id and assign filtered dataframe to current_user
#     for element_action in action_unique_values:
#         running_sum = 0
#         running_sum = current_user.action[current_user.action == action_unique_values[i]].count() #assign the count of the latest action to running_sum 
#         i=i+1
#         action_unique_values_df.set_value(j, element_action, running_sum) #add the latest count of that action to action_unique_values dataframe
#     j=j+1 #reindex so that we move to the next row when it looks at the next user
#     i=0 #reindex so that we start at the beginning of action_unique_values when we look at next user
#     
# writer = pd.ExcelWriter('first_batch_of_action_unique_values.xlsx')
# action_unique_values_df.to_excel(writer,'Sheet1')
# writer.save()

In [ ]:
# i=0 #key to action_unique_values
# j=1 #key to the ith row in new action_unique_values dataframe


# for element in sessions_data_pivoted['user_id']:
#     current_user = sessions_data[sessions_data.user_id == element] #filter dataframe for that user_id and assign filtered dataframe to current_user
#     for element_action in action_type_unique_values:
#         running_sum = 0
#         running_sum = current_user.action_type[current_user.action_type == action_type_unique_values[i]].count() #assign the count of the latest action to running_sum 
#         i=i+1
#         action_type_unique_values_df.set_value(j, element_action, running_sum) #add the latest count of that action to action_unique_values dataframe
#     j=j+1 #reindex so that we move to the next row when it looks at the next user
#     i=0 #reindex so that we start at the beginning of action_unique_values when we look at next user
    
# writer = pd.ExcelWriter('action_type_unique_values2.xlsx')
# action_type_unique_values_df.to_excel(writer,'Sheet1')
# writer.save()

In [ ]:
# i=0 #key to action_unique_values
# j=1 #key to the ith row in new action_unique_values dataframe


# for element in sessions_data_pivoted['user_id']:
#     current_user = sessions_data[sessions_data.user_id == element] #filter dataframe for that user_id and assign filtered dataframe to current_user
#     for element_action in device_type:
#         running_sum = 0
#         running_sum = current_user.device_type[current_user.device_type == device_type[i]].count() #assign the count of the latest action to running_sum 
#         i=i+1
#         device_type_df.set_value(j, element_action, running_sum) #add the latest count of that action to action_unique_values dataframe
#     j=j+1 #reindex so that we move to the next row when it looks at the next user
#     i=0 #reindex so that we start at the beginning of action_unique_values when we look at next user
    
# writer = pd.ExcelWriter('device_type.xlsx')
# device_type_df.to_excel(writer,'Sheet1')
# writer.save()

In [ ]:
# print(sessions_data_pivoted)
# writer = pd.ExcelWriter('user_id_and_secs_elapsed.xlsx')
# sessions_data_pivoted.to_excel(writer,'Sheet1')
# writer.save()


In [ ]:
# for element in sessions_data_pivoted['user_id']:
#     print(element)

In [ ]:
# #action_detail_unique_values

# i=0 #key to action_unique_values
# j=1 #key to the ith row in new action_unique_values dataframe


# for element in sessions_data_pivoted['user_id']:
#     current_user = sessions_data[sessions_data.user_id == element] #filter dataframe for that user_id and assign filtered dataframe to current_user
#     for element_action in action_detail_unique_values:
#         running_sum = 0
#         running_sum = current_user.action_detail[current_user.action_detail == action_detail_unique_values[i]].count() #assign the count of the latest action to running_sum 
#         i=i+1
#         action_detail_unique_values_df.set_value(j, element_action, running_sum) #add the latest count of that action to action_unique_values dataframe
#     j=j+1 #reindex so that we move to the next row when it looks at the next user
#     i=0 #reindex so that we start at the beginning of action_unique_values when we look at next user
    
# writer = pd.ExcelWriter('action_detail_unique_values.xlsx')
# action_detail_unique_values_df.to_excel(writer,'Sheet1')
# writer.save()

In [ ]:
# sessions_data[sessions_data.user_id == '0035hobuyj']

# current_user.action_detail[current_user.action_detail == action_detail_unique_values[i]].count()